// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywxkcsgqtnhwosewmnnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3eGtjc2dxdG5od29zZXdtbm53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5MTk5MjgsImV4cCI6MjA1NTQ5NTkyOH0.-a7yAaUvZdQIt9du4oqONOjzt3-NOIjGEfiOeA6HqlU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);